"""Sprint 6 — navigation.js Python ekvivalanı.

`admin-panel/frontend/src/data/navigation.js` içeriğini DocType'a seed
etmek için tek doğruluk kaynağı. Her record şu yapıda:

    {
      "key": "seller.store.profile_finans.profilim",   # benzersiz slug
      "parent": "seller.store.profile_finans",          # üst modül key
      "panel": "seller",                                # admin | seller
      "section": "store",                               # sidebar section
      "type": "item",                                   # section | group | item
      "label": "Profilim",
      "icon": "user-check",
      "color": None,                                    # group/section için
      "order": 0,
      "route": None,                                    # item için route veya doctype
      "doctype": "User Profile",
      "seller_owned": True,
      "requires": ["owner_or_co", "admin"],             # Module Policy seed kaynağı
      "is_protected": False,
    }

Seed patch (v15_6_2) bu listeyi gezip TH Module Registry kayıtları oluşturur.
Policy seed patch (v15_6_3) `requires` etiketlerinden TH Module Policy kayıtları
üretir (etiket → role_profile listesi map).
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Tag → Role Profile haritası
# ---------------------------------------------------------------------------
# navigation.js `requires:[...]` etiketleri çoğunlukla "owner_or_co", "admin"
# gibi rol-bazlı tag'ler. Bunları Role Profile adlarına çeviriyoruz.

REQUIRES_TAG_MAP: dict[str, list[str]] = {
	"owner": ["Seller Full Access"],
	"co_owner": ["Seller Co-Owner"],
	"owner_or_co": ["Seller Full Access", "Seller Co-Owner"],
	"admin": [],  # System Manager / Marketplace Admin platform admin
	"compliance": ["Compliance Manager"],
	"Buyer Full Access": ["Buyer Full Access"],
	"Buyer Approver L1": ["Buyer Approver L1"],
	"Buyer Approver L2": ["Buyer Approver L2"],
	"Buyer": ["Buyer Full Access", "Buyer Operations", "Buyer Finance Staff"],
}

# ---------------------------------------------------------------------------
# Tüm satıcı/admin profile'lar — denylist seed için
# ---------------------------------------------------------------------------
ALL_SELLER_PROFILES: list[str] = [
	"Seller Full Access",
	"Seller Co-Owner",
	"Seller Manager",
	"Seller Operations",
	"Seller Finance Staff",
]

ALL_BUYER_PROFILES: list[str] = [
	"Buyer Full Access",
	"Buyer Approver L1",
	"Buyer Approver L2",
	"Buyer Operations",
	"Buyer Finance Staff",
	"Buyer Viewer Only",
]


# ---------------------------------------------------------------------------
# SATICI panel modülleri
# ---------------------------------------------------------------------------
SELLER_MODULES: list[dict] = [
	# ─── SECTION: Dashboard ───
	{
		"key": "seller.dashboard",
		"type": "section",
		"panel": "seller",
		"section": "dashboard",
		"label": "Dashboard",
		"icon": "house",
		"color": "#7c3aed",
		"order": 0,
		"is_protected": True,
	},
	{
		"key": "seller.dashboard.main",
		"parent": "seller.dashboard",
		"type": "group",
		"panel": "seller",
		"section": "dashboard",
		"label": "",
		"order": 0,
	},
	{
		"key": "seller.dashboard.main.home",
		"parent": "seller.dashboard.main",
		"type": "item",
		"panel": "seller",
		"section": "dashboard",
		"label": "Dashboard",
		"icon": "layout-grid",
		"route": "/dashboard",
		"order": 0,
		"is_protected": True,
	},
	# ─── SECTION: Ürünlerim ───
	{
		"key": "seller.products",
		"type": "section",
		"panel": "seller",
		"section": "products",
		"label": "Ürünlerim",
		"icon": "package",
		"color": "#7c3aed",
		"order": 1,
	},
	{
		"key": "seller.products.urunler",
		"parent": "seller.products",
		"type": "group",
		"panel": "seller",
		"section": "products",
		"label": "Ürünler",
		"color": "#7c3aed",
		"order": 0,
	},
	{
		"key": "seller.products.urunler.urunlerim",
		"parent": "seller.products.urunler",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Ürünlerim",
		"icon": "list",
		"route": "/seller-listings",
		"order": 0,
	},
	{
		"key": "seller.products.urunler.kategorilerim",
		"parent": "seller.products.urunler",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Kategorilerim",
		"icon": "folder",
		"route": "/seller-categories",
		"order": 1,
	},
	{
		"key": "seller.products.toplu",
		"parent": "seller.products",
		"type": "group",
		"panel": "seller",
		"section": "products",
		"label": "Toplu Yükleme",
		"color": "#7c3aed",
		"order": 1,
	},
	{
		"key": "seller.products.toplu.yeni",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Yeni Toplu Yükleme",
		"icon": "upload",
		"route": "/bulk-import/new",
		"order": 0,
	},
	{
		"key": "seller.products.toplu.gecmis",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Yükleme Geçmişim",
		"icon": "history",
		"route": "/bulk-import",
		"order": 1,
	},
	{
		"key": "seller.products.toplu.kurallar",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Kurallarım",
		"icon": "zap",
		"route": "/my-eca-rules",
		"order": 2,
	},
	{
		"key": "seller.products.toplu.patternler",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Eşleştirmelerim",
		"icon": "wand",
		"route": "/my-regex-patterns",
		"order": 3,
	},
	{
		"key": "seller.products.toplu.feed",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "XML Feed",
		"icon": "cloud-download",
		"route": "/seller-feed",
		"order": 4,
	},
	{
		# MOGEM-665 — Ürün API'si bağlantısı (kimlik bilgisi, webhook, giden stok olayları)
		"key": "seller.products.toplu.api",
		"parent": "seller.products.toplu",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "API Bağlantısı",
		"icon": "plug",
		"route": "/seller-api",
		"order": 5,
	},
	{
		"key": "seller.products.katalog",
		"parent": "seller.products",
		"type": "group",
		"panel": "seller",
		"section": "products",
		"label": "Katalog Yapısı",
		"color": "#8b5cf6",
		"order": 2,
	},
	{
		"key": "seller.products.katalog.markalar",
		"parent": "seller.products.katalog",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Markalar",
		"icon": "bookmark",
		"doctype": "Brand",
		"order": 0,
	},
	{
		"key": "seller.products.katalog.tipler",
		"parent": "seller.products.katalog",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Ürün Tipleri",
		"icon": "layers",
		"doctype": "Product Type",
		"order": 1,
	},
	{
		"key": "seller.products.katalog.aileler",
		"parent": "seller.products.katalog",
		"type": "item",
		"panel": "seller",
		"section": "products",
		"label": "Ürün Aileleri",
		"icon": "package-2",
		"doctype": "Product Family",
		"order": 2,
	},
	# NOT: "Özellik Yönetimi" (Ürün Özellikleri + Özellik Setleri) satıcı panelinden
	# kaldırıldı — satıcı bunları yönetmiyor (Product Attribute backend'de spec
	# yazılırken otomatik bağlanır; Attribute Set admin işidir). Kayıtlar
	# patch v15_8_9 ile is_active=0 yapılır. Admin panelinde ilgili menü
	# admin-panel/frontend navigation.js üzerinden gelmeye devam eder.
	# ─── SECTION: Siparişlerim ───
	{
		"key": "seller.orders",
		"type": "section",
		"panel": "seller",
		"section": "orders",
		"label": "Siparişlerim",
		"icon": "shopping-bag",
		"color": "#10b981",
		"order": 2,
	},
	{
		"key": "seller.orders.rfq",
		"parent": "seller.orders",
		"type": "group",
		"panel": "seller",
		"section": "orders",
		"label": "RFQ",
		"color": "#f59e0b",
		"order": 0,
	},
	{
		"key": "seller.orders.rfq.talepler",
		"parent": "seller.orders.rfq",
		"type": "item",
		"panel": "seller",
		"section": "orders",
		"label": "RFQ Talepleri",
		"icon": "file-text",
		"route": "/rfq-list",
		"order": 0,
	},
	{
		"key": "seller.orders.rfq.teklifler",
		"parent": "seller.orders.rfq",
		"type": "item",
		"panel": "seller",
		"section": "orders",
		"label": "Tekliflerim",
		"icon": "send",
		"route": "/my-quotes",
		"order": 1,
	},
	{
		"key": "seller.orders.siparisler",
		"parent": "seller.orders",
		"type": "group",
		"panel": "seller",
		"section": "orders",
		"label": "Siparişler",
		"color": "#10b981",
		"order": 1,
	},
	{
		"key": "seller.orders.siparisler.list",
		"parent": "seller.orders.siparisler",
		"type": "item",
		"panel": "seller",
		"section": "orders",
		"label": "Siparişlerim",
		"icon": "shopping-bag",
		"route": "/seller-orders",
		"order": 0,
	},
	# ─── SECTION: Mağazam ───
	{
		"key": "seller.store",
		"type": "section",
		"panel": "seller",
		"section": "store",
		"label": "Mağazam",
		"icon": "store",
		"color": "#7c3aed",
		"order": 3,
		"is_protected": True,
	},
	{
		"key": "seller.store.profil",
		"parent": "seller.store",
		"type": "group",
		"panel": "seller",
		"section": "store",
		"label": "Profil & Finans",
		"color": "#f59e0b",
		"order": 0,
	},
	{
		"key": "seller.store.profil.profilim",
		"parent": "seller.store.profil",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Profilim",
		"icon": "user-check",
		"doctype": "User Profile",
		"seller_owned": True,
		"order": 0,
		"is_protected": True,
	},
	{
		"key": "seller.store.profil.magaza",
		"parent": "seller.store.profil",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Mağaza Ayarları",
		"icon": "store",
		"doctype": "Admin Seller Profile",
		"seller_owned": True,
		"order": 1,
		"requires": ["owner_or_co", "admin"],
	},
	{
		"key": "seller.store.profil.kyb",
		"parent": "seller.store.profil",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "KYB Doğrulama",
		"icon": "shield-check",
		"doctype": "KYB Verification",
		"seller_owned": True,
		"order": 2,
		"requires": ["owner", "admin"],
	},
	{
		# Saha/tedarikçi doğrulama başvurusu — KYB (işletme doğrulama) komşusu.
		# Rol kısıtı yok: create_my_verification session kullanıcısının satıcı
		# profiline bağlı, tüm satıcı personeli başvurabilir (Sertifikalarım gibi).
		"key": "seller.store.profil.dogrulama",
		"parent": "seller.store.profil",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Doğrulamalarım",
		"icon": "badge-check",
		"route": "/my-verifications",
		"order": 3,
	},
	{
		"key": "seller.store.profil.abonelik",
		"parent": "seller.store.profil",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Abonelik",
		"icon": "credit-card",
		"route": "/abonelik",
		"seller_owned": True,
		"order": 4,
		"requires": ["owner_or_co", "admin"],
	},
	{
		"key": "seller.store.sertifika",
		"parent": "seller.store",
		"type": "group",
		"panel": "seller",
		"section": "store",
		"label": "Sertifikalar",
		"color": "#059669",
		"order": 1,
	},
	{
		"key": "seller.store.sertifika.list",
		"parent": "seller.store.sertifika",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Sertifikalarım",
		"icon": "award",
		"route": "/my-certifications",
		"order": 0,
	},
	{
		"key": "seller.store.vitrin",
		"parent": "seller.store",
		"type": "group",
		"panel": "seller",
		"section": "store",
		"label": "Vitrin",
		"color": "#6366f1",
		"order": 2,
	},
	{
		"key": "seller.store.vitrin.layout",
		"parent": "seller.store.vitrin",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Sayfa Düzeni",
		"icon": "layout-grid",
		"route": "/storefront-layout",
		"order": 0,
	},
	{
		"key": "seller.store.vitrin.medya",
		"parent": "seller.store.vitrin",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Medya Kütüphanesi",
		"icon": "image",
		"route": "/media-library",
		"order": 1,
	},
	{
		"key": "seller.store.vitrin.medya_gezgini",
		"parent": "seller.store.vitrin",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Medya Gezgini",
		"icon": "folder",
		"route": "/my-media-explorer",
		"order": 2,
	},
	{
		"key": "seller.store.musteri",
		"parent": "seller.store",
		"type": "group",
		"panel": "seller",
		"section": "store",
		"label": "Müşteri & Sosyal",
		"color": "#8b5cf6",
		"order": 3,
	},
	{
		"key": "seller.store.musteri.mesajlar",
		"parent": "seller.store.musteri",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Mesajlarım",
		"icon": "message-square",
		"route": "/messaging/buyer-messages",
		"order": 0,
	},
	{
		"key": "seller.store.musteri.musaitlik",
		"parent": "seller.store.musteri",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Müsaitlik",
		"icon": "calendar",
		"route": "/messaging/availability",
		"order": 1,
	},
	{
		"key": "seller.store.musteri.yorum",
		"parent": "seller.store.musteri",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Yorumlarım",
		"icon": "star",
		"route": "/review-moderation",
		"order": 2,
	},
	{
		"key": "seller.store.musteri.soru",
		"parent": "seller.store.musteri",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Sorularım",
		"icon": "message-circle",
		"route": "/seller-questions",
		"order": 3,
	},
	{
		"key": "seller.store.musteri.galeri",
		"parent": "seller.store.musteri",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Galerim",
		"icon": "image",
		"doctype": "Seller Gallery Image",
		"seller_owned": True,
		"order": 4,
	},
	{
		"key": "seller.store.ekip",
		"parent": "seller.store",
		"type": "group",
		"panel": "seller",
		"section": "store",
		"label": "Ekip",
		"color": "#7c3aed",
		"order": 4,
		"requires": ["owner_or_co", "admin"],
	},
	{
		"key": "seller.store.ekip.ekibim",
		"parent": "seller.store.ekip",
		"type": "item",
		"panel": "seller",
		"section": "store",
		"label": "Ekibim",
		"icon": "users",
		"route": "/seller-team",
		"order": 0,
		"requires": ["owner_or_co", "admin"],
	},
	# ─── SECTION: CRM ───
	{
		"key": "seller.crm",
		"type": "section",
		"panel": "seller",
		"section": "crm",
		"label": "CRM",
		"icon": "briefcase",
		"color": "#8b5cf6",
		"order": 4,
	},
	{
		"key": "seller.crm.ozet",
		"parent": "seller.crm",
		"type": "group",
		"panel": "seller",
		"section": "crm",
		"label": "",
		"color": "#8b5cf6",
		"order": 0,
	},
	{
		"key": "seller.crm.ozet.dash",
		"parent": "seller.crm.ozet",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "CRM Özet",
		"icon": "layout-dashboard",
		"route": "/crm",
		"order": 0,
	},
	{
		"key": "seller.crm.satis",
		"parent": "seller.crm",
		"type": "group",
		"panel": "seller",
		"section": "crm",
		"label": "Satış",
		"color": "#8b5cf6",
		"order": 1,
	},
	{
		"key": "seller.crm.satis.deals",
		"parent": "seller.crm.satis",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Anlaşmalarım",
		"icon": "trending-up",
		"route": "/crm/deals",
		"order": 0,
	},
	{
		"key": "seller.crm.satis.leads",
		"parent": "seller.crm.satis",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Lead'lerim",
		"icon": "user-plus",
		"route": "/crm/leads",
		"order": 1,
	},
	{
		"key": "seller.crm.calisma",
		"parent": "seller.crm",
		"type": "group",
		"panel": "seller",
		"section": "crm",
		"label": "Çalışma",
		"color": "#7c3aed",
		"order": 2,
	},
	{
		"key": "seller.crm.calisma.mytasks",
		"parent": "seller.crm.calisma",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Görevlerim",
		"icon": "check-square",
		"route": "/crm/tasks?scope=mine",
		"order": 0,
	},
	{
		"key": "seller.crm.calisma.tasks",
		"parent": "seller.crm.calisma",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Tüm Görevler",
		"icon": "list-todo",
		"route": "/crm/tasks",
		"order": 1,
	},
	{
		"key": "seller.crm.calisma.notes",
		"parent": "seller.crm.calisma",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Notlar",
		"icon": "sticky-note",
		"route": "/crm/notes",
		"order": 2,
	},
	{
		"key": "seller.crm.kisiler",
		"parent": "seller.crm",
		"type": "group",
		"panel": "seller",
		"section": "crm",
		"label": "Kişiler",
		"color": "#6366f1",
		"order": 3,
	},
	{
		"key": "seller.crm.kisiler.contacts",
		"parent": "seller.crm.kisiler",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Kişiler",
		"icon": "users",
		"route": "/crm/contacts",
		"order": 0,
	},
	{
		"key": "seller.crm.kisiler.orgs",
		"parent": "seller.crm.kisiler",
		"type": "item",
		"panel": "seller",
		"section": "crm",
		"label": "Kurumlar",
		"icon": "building-2",
		"route": "/crm/organizations",
		"order": 1,
	},
	# ─── SECTION: Destek ───
	{
		"key": "seller.helpdesk",
		"type": "section",
		"panel": "seller",
		"section": "helpdesk",
		"label": "Destek",
		"icon": "life-buoy",
		"color": "#06b6d4",
		"order": 5,
	},
	# ─── SECTION: Lojistik (13-FE) ───
	# Satıcı kendi sevkiyatını kendisi paketliyor. Sidebar SATICIDA tamamen
	# DB-driven (frontend `sellerPanelSections` fail-secure gereği devreye
	# girmiyor), bu yüzden ekran route olarak var olsa bile registry kaydı
	# olmadan menüde HİÇ görünmüyor.
	#
	# G0 rol matrisi (2026-08-19): satıcıya sevkiyat listesi + paketleme +
	# teslimat açık; katalog, taşıyıcı hesapları ve lojistik ayarları platform
	# ekranı — admin menüsünde kalır. Menü kaydı YALNIZ ready ekranlara açılır
	# (kaynak: admin-panel logisticsScreens.js manifesti). I1 hâlâ bekliyor:
	# matriste satıcıya işaretli ama ekranı 15-FE'de açılacak.
	{
		"key": "seller.logistics",
		"type": "section",
		"panel": "seller",
		"section": "logistics",
		"label": "Lojistik",
		"icon": "truck",
		"color": "#f59e0b",
		"order": 6,
	},
	{
		"key": "seller.logistics.shipments",
		"parent": "seller.logistics",
		"type": "group",
		"panel": "seller",
		"section": "logistics",
		"label": "Sevkiyatlar",
		"color": "#f59e0b",
		"order": 0,
	},
	{
		"key": "seller.logistics.shipments.list",
		"parent": "seller.logistics.shipments",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Sevkiyatlar",
		"icon": "truck",
		"route": "/lojistik/sevkiyatlar",
		"order": 0,
	},
	{
		"key": "seller.logistics.shipments.create",
		"parent": "seller.logistics.shipments",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Manuel Sevkiyat",
		"icon": "file-plus",
		"route": "/lojistik/sevkiyatlar/yeni",
		"order": 1,
	},
	{
		"key": "seller.logistics.packing",
		"parent": "seller.logistics",
		"type": "group",
		"panel": "seller",
		"section": "logistics",
		"label": "Paketleme",
		"color": "#f59e0b",
		"order": 1,
	},
	{
		"key": "seller.logistics.packing.queue",
		"parent": "seller.logistics.packing",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Paketleme",
		"icon": "package",
		"route": "/lojistik/paketleme",
		"order": 0,
	},
	# ─── 14-FE · Teslimat (Ali) ───
	# G0 matrisi H0/D1/D2'yi satıcıya işaretledi (sellerVisible) ve ekranlar
	# 14-FE'de açıldı — kayıt bu yüzden şimdi ekleniyor. Satıcı kendi
	# teslimatının kanıtını kaydedebiliyor (14-FE karar defteri K-B) ve
	# kendi aracıyla teslim onun fiziksel işi (K-M).
	#
	# Tenant izolasyonu backend'de: menü kaydı yalnız KAPIYI açar, veri
	# sınırını değiştirmez (14-FE veri sözleşmesi §6.1).
	{
		"key": "seller.logistics.delivery",
		"parent": "seller.logistics",
		"type": "group",
		"panel": "seller",
		"section": "logistics",
		"label": "Teslimat",
		"color": "#f59e0b",
		"order": 2,
	},
	{
		"key": "seller.logistics.delivery.pod",
		"parent": "seller.logistics.delivery",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Teslim Kanıtı",
		"icon": "clipboard-check",
		"route": "/lojistik/teslim-kaniti",
		"order": 0,
	},
	{
		"key": "seller.logistics.delivery.seller_delivery",
		"parent": "seller.logistics.delivery",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Satıcı Teslimatı",
		"icon": "car",
		"route": "/lojistik/satici-teslimati",
		"order": 1,
	},
	{
		"key": "seller.logistics.delivery.buyer_pickup",
		"parent": "seller.logistics.delivery",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Alıcı Teslim Alma",
		"icon": "package-check",
		"route": "/lojistik/alici-teslim-alma",
		"order": 2,
	},
	# ─── 20-FE · Fiyatlandırma (Ali) ───
	# K1/K2/K3 satıcıya işaretli (manifestte `sellerVisible: true`). Gerekçe
	# 20-FE karar defteri K1/K2: satıcı KENDİ taşıyıcı anlaşmasını platform
	# üzerinden kullanabiliyor — kendi kuralını yazması ve kendi yükünü
	# hesaplatması bu yüzden onun işi, platformun değil.
	#
	# Etiketler satıcı diliyle yazılıyor ("Kargo fiyatlarım"), admin
	# menüsündeki "Tarifeler" ile aynı ekran ama aynı cümle değil: satıcı
	# kendi listesine bakıyor, platform herkesinkine.
	#
	# Maskeleme burada DEĞİL: platformun alış maliyeti backend'de
	# kırpılıyor (20-FE veri sözleşmesi §7.2). Menü kaydı yalnız kapıyı açar.
	{
		"key": "seller.logistics.pricing",
		"parent": "seller.logistics",
		"type": "group",
		"panel": "seller",
		"section": "logistics",
		"label": "Fiyatlandırma",
		"color": "#f59e0b",
		"order": 3,
	},
	{
		"key": "seller.logistics.pricing.rates",
		"parent": "seller.logistics.pricing",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Kargo Fiyatlarım",
		"icon": "coins",
		"route": "/lojistik/tarifeler",
		"order": 0,
	},
	{
		"key": "seller.logistics.pricing.rules",
		"parent": "seller.logistics.pricing",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Kargo Kurallarım",
		"icon": "list-ordered",
		"route": "/lojistik/fiyat-kurallari",
		"order": 1,
	},
	{
		"key": "seller.logistics.pricing.simulation",
		"parent": "seller.logistics.pricing",
		"type": "item",
		"panel": "seller",
		"section": "logistics",
		"label": "Fiyat Hesapla",
		"icon": "calculator",
		"route": "/lojistik/fiyat-simulasyonu",
		"order": 2,
	},
	{
		"key": "seller.helpdesk.main",
		"parent": "seller.helpdesk",
		"type": "group",
		"panel": "seller",
		"section": "helpdesk",
		"label": "",
		"color": "#06b6d4",
		"order": 0,
	},
	{
		"key": "seller.helpdesk.main.tickets",
		"parent": "seller.helpdesk.main",
		"type": "item",
		"panel": "seller",
		"section": "helpdesk",
		"label": "Destek Talepleri",
		"icon": "life-buoy",
		"route": "/helpdesk/tickets",
		"order": 0,
	},
]


# ---------------------------------------------------------------------------
# ADMIN panel modülleri (system section özelinde — tam liste seed sırası
# için anahtar olanlar)
# ---------------------------------------------------------------------------
# Not: admin panel'in 7 section'ı var (dashboard, catalog, commerce, sellers,
# crm, helpdesk, system). Burada sadece `system` section'ını detaylandırıyoruz
# çünkü `requires:[...]` etiketleri bu section'da yoğun. Diğer admin
# section'lar için tüm modüller "visible" varsayılan kalır.

ADMIN_MODULES: list[dict] = [
	# system section
	{
		"key": "admin.system",
		"type": "section",
		"panel": "admin",
		"section": "system",
		"label": "Sistem & Kullanıcılar",
		"icon": "settings",
		"color": "#7c3aed",
		"order": 6,
		"is_protected": True,
	},
	# Yetki & Kullanıcı grubu
	{
		"key": "admin.system.yetki",
		"parent": "admin.system",
		"type": "group",
		"panel": "admin",
		"section": "system",
		"label": "Yetki & Kullanıcı",
		"color": "#7c3aed",
		"order": 0,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.yetki.console",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Yetki Yönetimi",
		"icon": "shield-check",
		"route": "/permission-console",
		"order": 0,
		"requires": ["admin"],
		"is_protected": True,
	},
	{
		"key": "admin.system.yetki.simulator",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Yetki Simülatörü",
		"icon": "search",
		"route": "/authorization-simulator",
		"order": 1,
		"requires": ["admin"],
	},
	{
		"key": "admin.system.yetki.buyerteam",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "B2B Alıcı Ekibi",
		"icon": "users-round",
		"route": "/buyer-team",
		"order": 2,
		"requires": ["admin"],
	},
	{
		"key": "admin.system.yetki.approval",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Onay Kuyruğum",
		"icon": "check-circle",
		"route": "/approval-queue",
		"order": 3,
		"requires": ["Buyer Approver L1", "Buyer Approver L2", "admin"],
	},
	{
		"key": "admin.system.yetki.delegation",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Yetki Devri",
		"icon": "refresh-cw",
		"route": "/delegation",
		"order": 4,
		"requires": ["owner_or_co", "admin"],
	},
	{
		"key": "admin.system.yetki.owner_transfer",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Mağaza Sahibi Devri",
		"icon": "crown",
		"route": "/owner-transfer",
		"order": 5,
		"requires": ["owner", "admin"],
	},
	{
		"key": "admin.system.yetki.profiles",
		"parent": "admin.system.yetki",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Alıcı Profilleri",
		"icon": "user",
		"doctype": "User Profile",
		"order": 6,
		"requires": ["admin"],
	},
	# Uyum & Güvenlik grubu (Compliance Officer + Super Admin)
	{
		"key": "admin.system.uyum",
		"parent": "admin.system",
		"type": "group",
		"panel": "admin",
		"section": "system",
		"label": "Uyum & Güvenlik",
		"color": "#ef4444",
		"order": 1,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.pii",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "PII Mask Matrix",
		"icon": "shield",
		"route": "/compliance/pii-mask-matrix",
		"order": 0,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.anomaly",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Anomali Dashboard",
		"icon": "alert-triangle",
		"route": "/compliance/anomaly-dashboard",
		"order": 1,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.consent",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Onay Kayıtları",
		"icon": "check-circle",
		"doctype": "User Consent Log",
		"order": 2,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.export",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Veri Export Talepleri",
		"icon": "download",
		"doctype": "Data Export Request",
		"order": 3,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.dpa",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Veri İşleme Sözleşmeleri",
		"icon": "file-text",
		"doctype": "Data Processing Agreement",
		"order": 4,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.retention",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Veri Saklama Politikaları",
		"icon": "clock",
		"doctype": "Data Retention Policy",
		"order": 5,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.ropa",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "ROPA Kayıtları",
		"icon": "list-checks",
		"doctype": "Processing Activity Record",
		"order": 6,
		"requires": ["admin", "compliance"],
	},
	{
		"key": "admin.system.uyum.consent_v",
		"parent": "admin.system.uyum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Politika Versiyonları",
		"icon": "git-branch",
		"doctype": "Consent Policy Version",
		"order": 7,
		"requires": ["admin", "compliance"],
	},
	# Satınalma grubu
	{
		"key": "admin.system.procurement",
		"parent": "admin.system",
		"type": "group",
		"panel": "admin",
		"section": "system",
		"label": "Satınalma (Procurement)",
		"color": "#10b981",
		"order": 2,
		"requires": ["admin", "Buyer", "Buyer Full Access"],
	},
	{
		"key": "admin.system.procurement.cost",
		"parent": "admin.system.procurement",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Cost Center",
		"icon": "wallet",
		"route": "/procurement/cost-centers",
		"order": 0,
		"requires": ["admin", "Buyer"],
	},
	{
		"key": "admin.system.procurement.suppliers",
		"parent": "admin.system.procurement",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Onaylı Tedarikçiler",
		"icon": "handshake",
		"route": "/procurement/approved-suppliers",
		"order": 1,
		"requires": ["admin", "Buyer"],
	},
	# Görünüm grubu
	{
		"key": "admin.system.gorunum",
		"parent": "admin.system",
		"type": "group",
		"panel": "admin",
		"section": "system",
		"label": "Görünüm",
		"color": "#f59e0b",
		"order": 3,
		"requires": ["admin"],
	},
	{
		"key": "admin.system.gorunum.tema",
		"parent": "admin.system.gorunum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Site Teması",
		"icon": "palette",
		"route": "/theme-manager",
		"order": 0,
		"requires": ["admin"],
	},
	{
		"key": "admin.system.gorunum.banner",
		"parent": "admin.system.gorunum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Dashboard Banner",
		"icon": "megaphone",
		"doctype": "Dashboard Banner",
		"order": 1,
		"requires": ["admin"],
	},
	{
		"key": "admin.system.gorunum.notices",
		"parent": "admin.system.gorunum",
		"type": "item",
		"panel": "admin",
		"section": "system",
		"label": "Header Duyuruları",
		"icon": "megaphone",
		"route": "/header-notices",
		"order": 2,
		"requires": ["admin"],
	},
]


def get_all_modules() -> list[dict]:
	"""Tüm modül kayıtlarını tek listede döner — seed patch için."""
	return SELLER_MODULES + ADMIN_MODULES
