"""Storefront statik sayfa kayıtları (Faz 4c).

64 statik HTML sayfası için path → metadata. Admin paneli bu listeden
Static Page SEO record'larını seed eder ve render_static_page endpoint'i
path lookup için kullanır.

Yeni sayfa eklerken: bu listeye entry ekle, sonra
`bench execute tradehub_core.setup.seed_static_pages.run` çalıştır.

NGX-1 senkron notu (2026-07): dist'te HTML'i olmayan 9 hayalet path silindi
(/blog, /kariyer, /kurumsal-sorumluluk, /izleme, /haberler, /ortakliklar,
/kargo-koruma, /vergi, /satici/dogrulama) ve /markalar → /ureticiler'e
taşındı (nginx'te /markalar → 301 /ureticiler). Bu liste nginx
$seo_static_page_path map'i ile SENKRON tutulmalı; seed edilmiş eski DB
kayıtları `v15_seo_static_pages_cleanup` patch'i ile temizlenir.
"""

# Her entry: {
#   path: TR canonical path (örn. "/yardim-merkezi")
#   title: admin için display label
#   html_path: storefront dist relative path (örn. "pages/help/help-center.html")
#   indexable_default: seed sırasında noindex=0 yapılsın mı
#   sitemap_priority: 0.0-1.0 (string olarak)
#   sitemap_changefreq: always|hourly|daily|weekly|monthly|yearly|never
# }
STATIC_PAGES = [
	# ── Ana + listing (5) ─────────────────────────────────
	{
		"path": "/",
		"meta_title": "iStoc | Türkiye'nin B2B Toptan Satış Pazaryeri",
		"meta_description": "Türkiye'nin B2B toptan satış pazaryeri iStoc'ta doğrulanmış tedarikçilerden güvenli ödemeyle toptan ürün alın. Toptan fiyat avantajını keşfedin.",
		"title": "Anasayfa",
		"html_path": "index.html",
		"indexable_default": True,
		"sitemap_priority": "1.0",
		"sitemap_changefreq": "daily",
	},
	{
		"path": "/urunler",
		"meta_title": "Toptan Ürünler – Tüm Kategoriler | iStoc",
		"meta_description": "Elektronikten tekstile binlerce toptan ürünü fiyat, marka ve kategoriye göre karşılaştırın; doğrulanmış tedarikçilerden toptan fiyatına alın.",
		"title": "Tüm Ürünler",
		"html_path": "pages/products.html",
		"indexable_default": True,
		"sitemap_priority": "0.9",
		"sitemap_changefreq": "daily",
	},
	{
		"path": "/kategoriler",
		"meta_title": "Toptan Ürün Kategorileri | iStoc",
		"meta_description": "Elektronik, tekstil, kozmetik ve daha yüzlerce kategoride toptan ürünleri keşfedin; aradığınız toptan kategoriye tek sayfadan ulaşın.",
		"title": "Tüm Kategoriler",
		"html_path": "pages/categories.html",
		"indexable_default": True,
		"sitemap_priority": "0.8",
		"sitemap_changefreq": "weekly",
	},
	{
		"path": "/ureticiler",
		"meta_title": "Üreticiler ve Toptancılar | iStoc",
		"meta_description": "Türkiye'nin üretici, toptancı ve markalarını tek listede keşfedin; güvenilir tedarikçilerle doğrudan bağlantı kurun.",
		"title": "Tüm Markalar",
		"html_path": "pages/manufacturers.html",
		"indexable_default": True,
		"sitemap_priority": "0.7",
		"sitemap_changefreq": "weekly",
	},
	{
		"path": "/sepet",
		"title": "Sepet",
		"html_path": "pages/cart.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Auth (4, hepsi noindex) ───────────────────────────
	{
		"path": "/giris",
		"title": "Giriş",
		"html_path": "pages/auth/login.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/kayit",
		"title": "Kayıt Ol",
		"html_path": "pages/auth/register.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/sifremi-unuttum",
		"title": "Şifremi Unuttum",
		"html_path": "pages/auth/forgot-password.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/sifre-sifirla",
		"title": "Şifre Sıfırla",
		"html_path": "pages/auth/reset-password.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/davet-kabul",
		"title": "Daveti Kabul Et",
		"html_path": "pages/auth/accept-invite.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Yardım (6) ────────────────────────────────────────
	{
		"path": "/yardim-merkezi",
		"meta_title": "Yardım Merkezi | iStoc",
		"meta_description": "Sipariş takibi, iade, ödeme ve kargo konularında adım adım rehberler. Çözüm bulamazsanız destek ekibine buradan ulaşın.",
		"title": "Yardım Merkezi",
		"html_path": "pages/help/help-center.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/sss",
		"meta_title": "Sık Sorulan Sorular (SSS) | iStoc",
		"meta_description": "Alışveriş, ödeme, kargo, iade ve satıcılık hakkında en çok sorulan soruların net cevapları iStoc SSS sayfasında.",
		"title": "Sık Sorulan Sorular",
		"html_path": "pages/help/faq.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/sss/detay",
		"meta_title": "Soru Detayı – SSS | iStoc",
		"meta_description": "Sorunuzun ayrıntılı cevabını okuyun; ilgili rehberlere ve benzer sorulara bu sayfadan kolayca geçiş yapın.",
		"title": "SSS Detay",
		"html_path": "pages/help/faq-detail.html",
		"indexable_default": False,
		"sitemap_priority": "0.3",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/destek/yeni",
		"title": "Yeni Destek Talebi",
		"html_path": "pages/help/help-ticket-new.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/destek/taleplerim",
		"title": "Destek Taleplerim",
		"html_path": "pages/help/help-tickets.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/destek/talep",
		"title": "Destek Talep Detay",
		"html_path": "pages/help/help-ticket.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Bilgi (14) ────────────────────────────────────────
	{
		"path": "/satis-sonrasi",
		"meta_title": "Satış Sonrası Destek ve Korumalar | iStoc",
		"meta_description": "Garanti şartları, iade süreçleri ve teknik destek: iStoc'ta satış sonrası korumalarla toptan alışverişiniz güvence altında.",
		"title": "Satış Sonrası",
		"html_path": "pages/info/after-sales.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/odeme-secenekleri",
		"meta_title": "Ödeme Seçenekleri – Güvenli Ödeme | iStoc",
		"meta_description": "Kredi kartı, havale ve güvenceli ödeme seçenekleri iStoc'ta. Alıcı korumasıyla toptan siparişlerinizi risk almadan tamamlayın.",
		"title": "Ödeme Seçenekleri",
		"html_path": "pages/info/payments.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/iade-politikasi",
		"meta_title": "Para İade Politikası | iStoc",
		"meta_description": "Para iadesinin hangi koşullarda ve kaç günde yapıldığını öğrenin; iade talebi açma ve anlaşmazlık çözümü adımları bu sayfada.",
		"title": "İade Politikası",
		"html_path": "pages/info/refund-policy.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/kargo-lojistik",
		"meta_title": "Kargo ve Lojistik Süreçleri | iStoc",
		"meta_description": "Toptan siparişlerde kargo süreleri, sevkiyat takibi ve teslimat güvencesi: iStoc lojistik süreçlerinin tamamını inceleyin.",
		"title": "Kargo ve Lojistik",
		"html_path": "pages/info/shipping-logistics.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/ticaret-guvencesi/detay",
		"meta_title": "Ticari Güvence Nasıl Çalışır? | iStoc",
		"meta_description": "Ticari Güvence'nin adımlarını öğrenin: ödeme koruması, teslimat takibi ve anlaşmazlık çözümü süreçleri örneklerle bu sayfada.",
		"title": "Ticaret Güvencesi Detay",
		"html_path": "pages/info/trade-assurance-detail.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "monthly",
	},
	# ── Hukuki (10) ───────────────────────────────────────
	{
		"path": "/erisilebilirlik",
		"meta_title": "Erişilebilirlik Politikası | iStoc",
		"meta_description": "iStoc'un erişilebilirlik taahhüdü: uygulanan standartlar ve siteyi herkes için kullanılabilir kılan iyileştirmeler.",
		"title": "Erişilebilirlik",
		"html_path": "pages/legal/accessibility.html",
		"indexable_default": True,
		"sitemap_priority": "0.3",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/cerezler",
		"meta_title": "Çerez Politikası | iStoc",
		"meta_description": "iStoc'ta kullanılan çerez türlerini, kullanım amaçlarını ve çerez tercihlerinizi nasıl yöneteceğinizi adım adım öğrenin.",
		"title": "Çerez Politikası",
		"html_path": "pages/legal/cookies.html",
		"indexable_default": True,
		"sitemap_priority": "0.4",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/mesafeli-satis",
		"meta_title": "Mesafeli Satış Sözleşmesi | iStoc",
		"meta_description": "Mesafeli satış sözleşmesinin tam metni: cayma hakkı, teslimat süreleri, iade koşulları ve tarafların yükümlülükleri.",
		"title": "Mesafeli Satış Sözleşmesi",
		"html_path": "pages/legal/distance-sales.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/fikri-mulkiyet",
		"title": "Fikri Mülkiyet",
		"html_path": "pages/legal/ip.html",
		"indexable_default": False,
		"sitemap_priority": "0.3",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/kvkk",
		"title": "KVKK Aydınlatma Metni",
		"html_path": "pages/legal/kvkk.html",
		"indexable_default": False,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/yasal-uyari",
		"title": "Yasal Uyarı",
		"html_path": "pages/legal/notice.html",
		"indexable_default": False,
		"sitemap_priority": "0.3",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/gizlilik",
		"meta_title": "Gizlilik Politikası | iStoc",
		"meta_description": "iStoc gizlilik politikası: hangi verilerin toplandığı, nasıl korunduğu ve haklarınızı nasıl kullanacağınız bu sayfada.",
		"title": "Gizlilik Politikası",
		"html_path": "pages/legal/privacy.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/urun-listeleme-kurallari",
		"meta_title": "Ürün Listeleme Kuralları | iStoc",
		"meta_description": "Satıcılar için ürün listeleme kuralları: kategori seçimi, görsel ve içerik standartları ile fiyatlandırma ilkeleri rehberi.",
		"title": "Ürün Listeleme Kuralları",
		"html_path": "pages/legal/product-listing.html",
		"indexable_default": True,
		"sitemap_priority": "0.4",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/iade-kosullari",
		"title": "İade Koşulları",
		"html_path": "pages/legal/returns.html",
		"indexable_default": False,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "yearly",
	},
	{
		"path": "/kullanim-kosullari",
		"meta_title": "Kullanım Koşulları | iStoc",
		"meta_description": "iStoc B2B pazaryeri kullanım koşulları: üyelik, sipariş ve ödeme kuralları ile alıcı-satıcı yükümlülüklerinin güncel metni.",
		"title": "Kullanım Koşulları",
		"html_path": "pages/legal/terms.html",
		"indexable_default": True,
		"sitemap_priority": "0.5",
		"sitemap_changefreq": "yearly",
	},
	# ── Dashboard (14, hepsi noindex) ─────────────────────
	{
		"path": "/hesabim/adresler",
		"title": "Adreslerim",
		"html_path": "pages/dashboard/addresses.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim",
		"title": "Hesabım",
		"html_path": "pages/dashboard/buyer-dashboard.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/kisiler",
		"title": "Kişilerim",
		"html_path": "pages/dashboard/contacts.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/favoriler",
		"title": "Favorilerim",
		"html_path": "pages/dashboard/favorites.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/sorularim",
		"title": "Sorularım",
		"html_path": "pages/dashboard/inquiries.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/kyb",
		"title": "KYB Doğrulama",
		"html_path": "pages/dashboard/kyb.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/mesajlar",
		"title": "Mesajlarım",
		"html_path": "pages/dashboard/messages.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/siparisler",
		"title": "Siparişlerim",
		"html_path": "pages/dashboard/orders.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/odeme",
		"title": "Ödeme Yöntemlerim",
		"html_path": "pages/dashboard/payment.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/profil",
		"title": "Profilim",
		"html_path": "pages/dashboard/profile.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/rfq",
		"title": "RFQ Taleplerim",
		"html_path": "pages/dashboard/rfq.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/rfq/yeni",
		"title": "Yeni RFQ",
		"html_path": "pages/dashboard/rfq-form.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/rfq/teklifler",
		"title": "RFQ Teklifleri",
		"html_path": "pages/dashboard/rfq-quotes.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/hesabim/ayarlar",
		"title": "Hesap Ayarları",
		"html_path": "pages/dashboard/settings.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Order (4, hepsi noindex) ──────────────────────────
	{
		"path": "/odeme",
		"title": "Ödeme Sayfası",
		"html_path": "pages/order/checkout.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/odeme/basarili",
		"title": "Ödeme Başarılı",
		"html_path": "pages/order/order-success.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/odeme/basarisiz",
		"title": "Ödeme Başarısız",
		"html_path": "pages/order/payment-failed.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/odeme/isleniyor",
		"title": "Ödeme İşleniyor",
		"html_path": "pages/order/payment-processing.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Seller (7) ────────────────────────────────────────
	{
		"path": "/satici-ol",
		"meta_title": "Satıcı Ol – Toptan Satış Yapın | iStoc",
		"meta_description": "Ürünlerinizi binlerce B2B alıcısına satın. Başvuru ücretsiz: mağazanızı açın, toptan satışa bugün başlayın.",
		"title": "Satıcı Ol",
		"html_path": "pages/seller/sell.html",
		"indexable_default": True,
		"sitemap_priority": "0.7",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/satici/fiyatlandirma",
		"meta_title": "Satıcı Paketleri ve Komisyonlar | iStoc",
		"meta_description": "Satıcı üyelik paketlerini, komisyon oranlarını ve fiyatlandırmayı karşılaştırın; işletmenize uygun planla satışa başlayın.",
		"title": "Satıcı Fiyatlandırması",
		"html_path": "pages/seller/sell-pricing.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "monthly",
	},
	{
		"path": "/satici/dashboard",
		"title": "Satıcı Paneli",
		"html_path": "pages/seller/dashboard.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/satici/basvuru-bekleyen",
		"title": "Başvuru Bekleniyor",
		"html_path": "pages/seller/application-pending.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/satici/tedarikci-kurulum",
		"title": "Tedarikçi Kurulumu",
		"html_path": "pages/seller/supplier-setup.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	{
		"path": "/satici/vitrin",
		"title": "Satıcı Vitrini",
		"html_path": "pages/seller/seller-storefront.html",
		"indexable_default": False,
		"sitemap_priority": "0.1",
		"sitemap_changefreq": "never",
	},
	# ── Top + Special (5) ─────────────────────────────────
	{
		"path": "/firsatlar",
		"meta_title": "Toptan Kampanyalar ve Fırsat Ürünleri | iStoc",
		"meta_description": "Güncel kampanyalı toptan ürünler ve indirimli fırsatlar iStoc'ta. Stoklarla sınırlı toptan fiyat avantajlarını kaçırmayın.",
		"title": "Fırsatlar",
		"html_path": "pages/top-deals.html",
		"indexable_default": True,
		"sitemap_priority": "0.7",
		"sitemap_changefreq": "daily",
	},
	{
		"path": "/cok-satanlar",
		"meta_title": "En Çok Satan Toptan Ürünler | iStoc",
		"meta_description": "iStoc'ta en çok satan toptan ürünleri görün; popüler kategorilerde öne çıkan tedarikçileri karşılaştırıp siparişinizi hemen verin.",
		"title": "Çok Satanlar",
		"html_path": "pages/top-ranking.html",
		"indexable_default": True,
		"sitemap_priority": "0.7",
		"sitemap_changefreq": "daily",
	},
	{
		"path": "/cok-satanlar/kategori",
		"meta_title": "Kategoriye Göre En Çok Satanlar | iStoc",
		"meta_description": "Her kategorinin en çok satan toptan ürünlerini ayrı ayrı inceleyin; talep gören ürünlerle stoğunuzu doğru planlayın.",
		"title": "Kategoriye Göre Çok Satanlar",
		"html_path": "pages/top-ranking-category.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "daily",
	},
	{
		"path": "/size-ozel",
		"title": "Size Özel Seçimler",
		"html_path": "pages/tailored-selections.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "weekly",
	},
	{
		"path": "/ticaret-guvencesi",
		"meta_title": "Ticari Güvence – Güvenli Toptan Alışveriş | iStoc",
		"meta_description": "iStoc Ticari Güvence ile ödemeniz teslimata kadar korumada: güvenli ödeme, para iade garantisi ve sevkiyat takibi tek pakette.",
		"title": "Ticaret Güvencesi",
		"html_path": "pages/trade-assurance.html",
		"indexable_default": True,
		"sitemap_priority": "0.6",
		"sitemap_changefreq": "monthly",
	},
	# ── 404 ───────────────────────────────────────────────
	{
		"path": "/404",
		"title": "Sayfa Bulunamadı",
		"html_path": "404.html",
		"indexable_default": False,
		"sitemap_priority": "0.0",
		"sitemap_changefreq": "never",
	},
]


def find_entry(path: str) -> dict | None:
	"""Path'e göre registry entry döner; yoksa None."""
	if not path:
		return None
	for entry in STATIC_PAGES:
		if entry["path"] == path:
			return entry
	return None


def indexable_paths() -> list[str]:
	"""indexable_default=True olan path'lerin listesi."""
	return [e["path"] for e in STATIC_PAGES if e.get("indexable_default")]
