"""Canonical Listing fields with TR+EN synonyms for TF-IDF matching."""

CANONICAL_FIELDS: dict[str, list[str]] = {
	"sku": [
		"sku",
		"stok kodu",
		"ürün kodu",
		"urun kodu",
		"kod",
		"code",
		"stock code",
		"product code",
		"model kodu",
		"part no",
		"item no",
		"barcode",
		"barkod",
	],
	"title": [
		"ürün adı",
		"urun adi",
		"ürün ismi",
		"ad",
		"isim",
		"title",
		"name",
		"product name",
		"model adı",
		"mal adı",
		"ürün başlığı",
	],
	"base_price": [
		"fiyat",
		"birim fiyat",
		"fiat",
		"price",
		"tutar",
		"ücret",
		"ucret",
		"satış fiyatı",
		"vergi hariç",
		"vergi dahil",
		"unit price",
		"sale price",
		"list price",
		"kdv hariç",
		"kdv dahil",
	],
	"selling_price": [
		"satış fiyatı",
		"indirimli fiyat",
		"promosyon fiyatı",
		"kampanya",
		"indirimli",
		"discount price",
		"sale price",
		"promotion",
	],
	"stock_qty": [
		"stok",
		"stock",
		"adet",
		"miktar",
		"qty",
		"quantity",
		"mevcut stok",
		"depo",
		"envanter",
		"available stock",
		"kalan",
	],
	"min_order_qty": [
		"min sipariş",
		"minimum sipariş",
		"asgari sipariş",
		"moq",
		"minimum order",
		"min order qty",
		"minimum miktar",
	],
	"product_category": [
		"kategori",
		"category",
		"ürün kategorisi",
		"sınıf",
		"tür",
		"grup",
		"department",
		"product category",
		"kategori adı",
	],
	"brand": [
		"marka",
		"brand",
		"marka adı",
		"üretici",
		"manufacturer",
		"label",
	],
	"short_description": [
		"kısa açıklama",
		"özet",
		"summary",
		"short description",
		"highlights",
		"öne çıkanlar",
	],
	"description": [
		"açıklama",
		"aciklama",
		"detay",
		"description",
		"details",
		"uzun açıklama",
		"ürün açıklaması",
		"product description",
	],
	"tags": [
		"etiketler",
		"etiket",
		"tags",
		"keywords",
		"anahtar kelimeler",
		"hashtag",
		"labels",
	],
	"weight": [
		"ağırlık",
		"agirlik",
		"weight",
		"kargo ağırlığı",
		"shipping weight",
		"net ağırlık",
		"net weight",
	],
	"barcode": [
		"barkod",
		"barcode",
		"gtin",
		"ean",
		"ean13",
		"ean-13",
		"upc",
	],
	"discount_percentage": [
		"indirim oranı",
		"indirim yüzdesi",
		"discount",
		"discount percent",
		"kampanya yüzdesi",
		"promo %",
		"% indirim",
	],
	"primary_image": [
		"ana resim",
		"ürün resmi",
		"image",
		"primary image",
		"main image",
		"fotograf",
		"fotoğraf",
		"görsel",
		"image url",
	],
}


def get_all_targets() -> list[str]:
	"""Tüm canonical field adlarını döndür."""
	return list(CANONICAL_FIELDS.keys())


def build_corpus() -> list[tuple[str, str]]:
	"""Returns list of (field_name, synonym_text) tuples for TF-IDF fitting."""
	corpus: list[tuple[str, str]] = []
	for field, synonyms in CANONICAL_FIELDS.items():
		for syn in synonyms:
			corpus.append((field, syn))
	return corpus
