"""Canonical Listing fields with TR+EN synonyms for TF-IDF matching."""

CANONICAL_FIELDS: dict[str, list[str]] = {
	"sku": [
		"sku",
		"stok kodu",
		"ürün kodu",
		"urun kodu",
		"kod",
		"code",
		"stock code",
		"product code",
		"model kodu",
		"model code",
		"part no",
		"part number",
		"item no",
		"item code",
		"sku code",
		"barcode",
		"barkod",
	],
	"title": [
		"ürün adı",
		"urun adi",
		"ürün ismi",
		"ad",
		"isim",
		"title",
		"name",
		"product name",
		"item name",
		"product title",
		"model name",
		"model adı",
		"mal adı",
		"ürün başlığı",
	],
	"base_price": [
		"fiyat",
		"birim fiyat",
		"fiat",
		"price",
		"tutar",
		"ücret",
		"ucret",
		"satış fiyatı",
		"vergi hariç",
		"vergi dahil",
		"unit price",
		"base price",
		"sale price",
		"list price",
		"price excl tax",
		"price incl tax",
		"kdv hariç",
		"kdv dahil",
	],
	"selling_price": [
		"satış fiyatı",
		"indirimli fiyat",
		"promosyon fiyatı",
		"kampanya",
		"indirimli",
		"selling price",
		"discounted price",
		"discount price",
		"sale price",
		"special price",
		"promotion",
		"promo price",
	],
	"stock_qty": [
		"stok",
		"stock",
		"adet",
		"miktar",
		"qty",
		"quantity",
		"mevcut stok",
		"depo",
		"envanter",
		"available stock",
		"available qty",
		"stock qty",
		"stock quantity",
		"inventory",
		"on hand",
		"kalan",
	],
	"min_order_qty": [
		"min sipariş",
		"minimum sipariş",
		"asgari sipariş",
		"moq",
		"minimum order",
		"min order",
		"min order qty",
		"minimum order quantity",
		"minimum miktar",
	],
	"product_category": [
		"kategori",
		"category",
		"ürün kategorisi",
		"sınıf",
		"grup",
		"department",
		"product category",
		"category name",
		"kategori adı",
	],
	"brand": [
		"marka",
		"brand",
		"brand name",
		"marka adı",
		"üretici",
		"manufacturer",
		"maker",
		"label",
	],
	"short_description": [
		"kısa açıklama",
		"özet",
		"summary",
		"short description",
		"brief",
		"highlights",
		"öne çıkanlar",
	],
	"description": [
		"açıklama",
		"aciklama",
		"detay",
		"description",
		"details",
		"long description",
		"full description",
		"uzun açıklama",
		"ürün açıklaması",
		"product description",
	],
	"tags": [
		"etiketler",
		"etiket",
		"tags",
		"tag",
		"keywords",
		"anahtar kelimeler",
		"hashtag",
		"labels",
	],
	"weight": [
		"ağırlık",
		"agirlik",
		"weight",
		"kargo ağırlığı",
		"shipping weight",
		"gross weight",
		"net ağırlık",
		"net weight",
		"package weight",
	],
	"barcode": [
		"barkod",
		"barcode",
		"bar code",
		"gtin",
		"ean",
		"ean13",
		"ean-13",
		"upc",
		"isbn",
	],
	"discount_percentage": [
		"indirim oranı",
		"indirim yüzdesi",
		"discount",
		"discount percent",
		"discount percentage",
		"discount rate",
		"kampanya yüzdesi",
		"promo %",
		"% indirim",
	],
	"primary_image": [
		"ana resim",
		"ürün resmi",
		"image",
		"primary image",
		"main image",
		"photo",
		"picture",
		"fotograf",
		"fotoğraf",
		"görsel",
		"image url",
		"image link",
	],
	# [mini-PIM LINK] — statik şablon başlıklarıyla birebir eşleşir
	"product_type": [
		"product type",
		"ürün tipi",
		"urun tipi",
		"ürün tipi adı",
		"tip",
		"type",
	],
	"product_family": [
		"product family",
		"ürün ailesi",
		"urun ailesi",
		"aile",
		"family",
	],
	"attribute_set": [
		"attribute set",
		"özellik seti",
		"ozellik seti",
		"nitelik seti",
		"attr set",
	],
	# [VARYANT BLOĞU] — persister `variant_axis_N_type` / `_value` okur
	"parent_sku": [
		"parent sku",
		"ana sku",
		"ana stok kodu",
		"üst sku",
		"ust sku",
		"parent stock code",
	],
	"variant_sku": [
		"variant sku",
		"varyant sku",
		"varyant stok kodu",
		"variant stock code",
	],
	"variant_axis_1_type": [
		"variant axis 1 name",
		"varyant ekseni 1 adı",
		"varyant ekseni 1 adi",
		"varyant 1 adı",
		"eksen 1 adı",
		"axis 1 name",
	],
	"variant_axis_1_value": [
		"variant axis 1 value",
		"varyant ekseni 1 değeri",
		"varyant ekseni 1 degeri",
		"varyant 1 değeri",
		"eksen 1 değeri",
		"axis 1 value",
	],
	"variant_axis_2_type": [
		"variant axis 2 name",
		"axis 2 name",
		"varyant ekseni 2 adı",
		"varyant ekseni 2 adi",
		"varyant 2 adı",
		"eksen 2 adı",
	],
	"variant_axis_2_value": [
		"variant axis 2 value",
		"axis 2 value",
		"varyant ekseni 2 değeri",
		"varyant ekseni 2 degeri",
		"varyant 2 değeri",
		"eksen 2 değeri",
	],
	"variant_axis_3_type": [
		"variant axis 3 name",
		"axis 3 name",
		"varyant ekseni 3 adı",
		"varyant ekseni 3 adi",
		"varyant 3 adı",
		"eksen 3 adı",
	],
	"variant_axis_3_value": [
		"variant axis 3 value",
		"axis 3 value",
		"varyant ekseni 3 değeri",
		"varyant ekseni 3 degeri",
		"varyant 3 değeri",
		"eksen 3 değeri",
	],
	"variant_price": [
		"variant price",
		"varyant fiyatı",
		"varyant fiyati",
		"varyant fiyat",
	],
	"variant_stock": [
		"variant stock",
		"varyant stok",
		"varyant stoğu",
		"varyant stogu",
	],
}


def get_all_targets() -> list[str]:
	"""Tüm canonical field adlarını döndür."""
	return list(CANONICAL_FIELDS.keys())


def build_corpus() -> list[tuple[str, str]]:
	"""Returns list of (field_name, synonym_text) tuples for TF-IDF fitting."""
	corpus: list[tuple[str, str]] = []
	for field, synonyms in CANONICAL_FIELDS.items():
		for syn in synonyms:
			corpus.append((field, syn))
	return corpus
